language: node_js
node_js:
  - '12'
script:
  - echo '=====Building starts====='
  - echo 'Installing dependencies'
  - npm install
  - echo 'Building app'
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: gdBloTXTzQZoyhYAJCIOfq5XpC6/dkssvk3ivqO8ijwOWJs0Dqzb3Id/Zq9s4dygIlqDRhu/a9gtYKjNSJVqnTrTisU27RDTUeytQCvkarKUxZfVdzifIFtxX8TJQ48txfpZOulyHoOA6U/U9Afxcy37ruMtd+Dsv3y8XNUGeCBpKQrixy5xl05T+IagLz9blgdPhYVJaIHHcxsVPNPoeYeTZGRj3hq03Pl79kOmiBIwmGY0QKwUf1CQV4bjEgDkgja1nfDgtEADA2sBBsOKHAQQ+0XpBcXEiybqV32SO7HPYyokSR9vS2OfqHiF+KnBO47Y0aZMlAtkvDIT3o2fH36b6uG6N7YiQy27sN2KDhNuNluSKa9YVcJ6VgWcy63rFijNLdv//sZCpQ4LKBaQlrtw/6m/QDLFuoRCozBa9XrajLWnNKzdfCVi4Pc9oVvGxuAKVeDV5QGTbThCqFy4FCFYd40+GVOC6TRBShJWVu4in6rAbi4keBjzIUX+3CvXxqSLYUKHrmHzgKFSjhlxFNMybftba3sv4CoZ3CKIZuwlKwanxbm4qJspn8qNKyZDXqnwLXRHBxOSySb4DnxPNtvx9dY2M9X2eA7/ehzgLPY7G5bMtHZJEvt7mM45lWoTWH1ecXsQZClycuOUZAlVlYDSR9NWJI9KJY73O9Vy8JQ=
  app: moozcl
  on:
    repo: niles87/zoom_clone
  skip_cleanup: 'true'
